pipeline{
    agent any
    environment{
        DOCKER_REPO_URI = "372641111498.dkr.ecr.ap-south-1.amazonaws.com"
        DOCKER_REPO_NAME = "thread-app"
    }
    stages{
        stage("Read app version to attach as image tag"){
            steps{
                script{
                    APP_VERSION = sh(
                        script: "node -p \"require('./application/package.json').version\"",
                        returnStdout: true
                    ).trim()

                    echo "Application Version: ${APP_VERSION}"
                    env.IMAGE_TAG = "${APP_VERSION}-${BUILD_NUMBER}"
                    env.IMAGE_NAME = "${DOCKER_REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }
        stage("Login into ECR repository"){
            steps{
                script{
                    echo "Login into ECR repository......."

                    withCredentials([usernamePassword(
                        credentialsId: 'aws-credential',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )]){
                        sh "export AWS_DEFAULT_REGION=ap-south-1"
                        sh "export AWS_DEFAULT_OUTPUT=json"
                        sh "aws ecr get-login-password | docker login --username AWS --password-stdin ${DOCKER_REPO_URI}"
                    }
                }
            }
        }
        stage("Build and push image"){
            steps{
                script{
                    echo "Build the docker image......."
                    sh "docker build -t ${IMAGE_NAME} -f docker/Dockerfile ."
                    
                    echo "Tag the image......."
                    sh "docker tag ${IMAGE_NAME} ${DOCKER_REPO_URI}/${IMAGE_NAME}"

                    echo "Push image into repository......."
                    sh "docker push ${DOCKER_REPO_URI}/${IMAGE_NAME}"
                }
            }
        }
        stage("Deploy application on kubernetes"){
            environment{
                NAMESPACE = "thread-app-ns"
            }
            steps{
                script{
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'aws-credential',
                            usernameVariable: 'AWS_ACCESS_KEY_ID',
                            passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                        ),
                        string(credentialsId: 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY', variable: 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY'),
                        string(credentialsId: 'CLERK_SECRET_KEY', variable: 'CLERK_SECRET_KEY'),
                        string(credentialsId: 'NEXT_CLERK_WEBHOOK_SECRET', variable: 'NEXT_CLERK_WEBHOOK_SECRET'),
                        string(credentialsId: 'MONGODB_URL', variable: 'MONGODB_URL')
                    ]){
                        sh '''
                        export AWS_DEFAULT_REGION=ap-south-1
                        export AWS_DEFAULT_OUTPUT=json

                        echo "Connecting with eks cluster....."
                        aws eks update-kubeconfig --name thread-app-eks-cluster

                        echo "Create namespace"
                        kubectl create namespace ${NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -

                        echo "Creating secret component"
                        kubectl create secret generic thread-app-secrets \
                            --namespace ${NAMESPACE} \
                            --from-literal=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}" \
                            --from-literal=CLERK_SECRET_KEY="${CLERK_SECRET_KEY}" \
                            --from-literal=NEXT_CLERK_WEBHOOK_SECRET="${NEXT_CLERK_WEBHOOK_SECRET}" \
                            --from-literal=MONGODB_URL="${MONGODB_URL}" \
                            --dry-run=client -o yaml | kubectl apply --namespace ${NAMESPACE} -f -

                        echo "Create deployments with dummy image"
                        kubectl apply --namespace ${NAMESPACE} -f kubernetes/thread-app-deployment.yaml

                        echo "Update image in deployment"
                        kubectl set image deployment/thread-app-deployment \
                            thread-app=${DOCKER_REPO_URI}/${IMAGE_NAME} \
                            --namespace ${NAMESPACE}

                        echo "Waiting for rollout across all the pods"
                        kubectl rollout status deployment/thread-app-deployment \
                            --namespace ${NAMESPACE}

                        echo "Create external service"
                        kubectl apply --namespace ${NAMESPACE} -f kubernetes/thread-app-service.yaml

                        echo "Check deployment and services"
                        kubectl get deployments --namespace ${NAMESPACE}
                        kubectl get services --namespace ${NAMESPACE}
                        '''
                    }
                }
            }
        }
    }
}