---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: demo
type: Opaque
stringData:
  access-key: "xxx"
  secret-access-key: "xxx/+xxx"

---

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: "sre-secret-store"
  namespace: "demo"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2" 
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-south-1"
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret-access-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "sre-external-secret"
  namespace: "demo"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: "sre-secret-store"
    kind: SecretStore
  target:
    name: prod-secrets
  dataFrom:
    - extract:
        key: "NGINX-SECRET"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: "demo"
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        envFrom:
          - secretRef:
              name: prod-secrets 