---
- name: Create jenkins credential
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files:
    - jenkins-credentials.yaml
  
  tasks:
    - name: Generate Jenkins API token
      community.general.jenkins_credential:
        id: "automation-token"
        name: "automation-token"
        url: "{{ jenkins_url }}"
        jenkins_user: "{{ jenkins_user }}"
        jenkins_password: "{{ jenkins_password }}"
        type: "token"
      register: token_result

    - name: Create github credential
      community.general.jenkins_credential:
        url: "{{ jenkins_url }}"
        jenkins_user: "{{ jenkins_user }}"
        token: "{{ token_result.token }}" 
        id: "github-credential"
        type: "user_and_pass"
        username: "{{ github_username }}"
        password: "{{ github_pat }}"
        state: present

    - name: Create AWS credential
      community.general.jenkins_credential:
        url: "{{ jenkins_url }}"
        jenkins_user: "{{ jenkins_user }}"
        token: "{{ token_result.token }}" 
        id: "aws-credential"
        type: "user_and_pass"
        username: "{{ aws_access_key }}"
        password: "{{ aws_secret_key }}"
        state: present
      
    - name: Create environment variable as credential
      community.general.jenkins_credential:
        url: "{{ jenkins_url }}"
        jenkins_user: "{{ jenkins_user }}"
        token: "{{ token_result.token }}"
        id: "{{ item.id }}"
        type: "text"
        secret: "{{ item.secret }}"
        state: present
      loop:
        - { id: "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", secret: "{{ NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" }
        - { id: "CLERK_SECRET_KEY", secret: "{{ CLERK_SECRET_KEY }}" }
        - { id: "NEXT_CLERK_WEBHOOK_SECRET", secret: "{{ NEXT_CLERK_WEBHOOK_SECRET }}" }
        - { id: "MONGODB_URL", secret: "{{ MONGODB_URL }}" }

    - name: Create email credential
      community.general.jenkins_credential:
        url: "{{ jenkins_url }}"
        jenkins_user: "{{ jenkins_user }}"
        token: "{{ token_result.token }}" 
        id: "gmail-smpt-credential"
        type: "user_and_pass"
        username: "{{ sender_email }}"
        password: "{{ app_password }}"
        state: present