jenkins_url: ""
jenkins_user: ""
jenkins_password: ""

github_username: ""
github_pat: ""

aws_access_key: ""
aws_secret_key: ""

NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ""
CLERK_SECRET_KEY: ""
NEXT_CLERK_WEBHOOK_SECRET: ""
MONGODB_URL: ""
